# -*- coding: utf-8 -*-
# config.yaml
# Configuration file for seisplot.py

# Traces per inch   (less -> bigger plot)
tpi: 50

# Inches per second (more -> bigger plot)
ips: 3

# Wiggle skips (1 -> no skips, 2 -> every 2nd trace, etc.)
skip: 2

# Seismic data display parameters (wiggle, varden, both):
display: both

# Multiplication factor for amplitudes 
gain: 2

# Wiggle fill: RGB, 0-255, opacity: 0-1
colour: 
  - 0
  - 0
  - 0
opacity: 0.5

# Wiggle plot lineweight
lineweight: 0.2

# Colormap for variable density
# e.g. matplotlib colourbars: Greys (black to white), RdBu, etc.
# See more at http://matplotlib.org/examples/color/colormaps_reference.html
cmap: Greys

# Fontsize
fontsize: 10

# Watermark
watermark_text: Â© A Seismic Company
watermark_size: 12
watermark_colour: white

# Stupid things
stain_paper: false
coffee_rings: 0
