# -*- coding: utf-8 -*-
# config.yaml
# Configuration file for seisplot.py

# Traces per inch   (less -> bigger plot)
tpi: 100

# Inches per second (more -> bigger plot)
ips: 2

# Wiggle skips (1 -> no skips, 2 -> every 2nd trace, etc.)
skip: 10

# Multiplication factor for amplitudes 
gain: 2

# Fontsize
fontsize: 10

# Wiggle fill: RGB, 0-255, opacity: 0-1
colour: 
  - 0
  - 0
  - 0
opacity: 0.5

# Wiggle plot lineweight
lineweight: 0.2

# Colormap for variable density
cmap: 'RdBu'

# Turn seismic gridlines 'on' or 'off'
seis_grid: 'off'

# Seismic data display parameters (wiggle, varden, both):
display: both
